import json
from datetime import datetime, timezone
from app import db


class StudyPlan(db.Model):
    __tablename__ = "study_plans"

    id = db.Column(db.Integer, primary_key=True)
    title = db.Column(db.String(255), nullable=False)
    goal = db.Column(db.Text)
    duration_days = db.Column(db.Integer, default=7)

    # JSON list of daily study tasks generated by AI
    plan_content = db.Column(db.Text)

    document_id = db.Column(db.Integer, db.ForeignKey("documents.id"), nullable=False)
    document = db.relationship("Document", back_populates="study_plans")
    student_id = db.Column(db.Integer, db.ForeignKey("users.id"), nullable=False)
    student = db.relationship("User", back_populates="study_plans")

    created_at = db.Column(db.DateTime, default=lambda: datetime.now(timezone.utc))
    updated_at = db.Column(
        db.DateTime,
        default=lambda: datetime.now(timezone.utc),
        onupdate=lambda: datetime.now(timezone.utc),
    )

    def to_dict(self):
        return {
            "id": self.id,
            "title": self.title,
            "goal": self.goal,
            "durationDays": self.duration_days,
            "planContent": json.loads(self.plan_content) if self.plan_content else [],
            "documentId": self.document_id,
            "studentId": self.student_id,
            "createdAt": self.created_at.isoformat(),
        }
